### ISSUE TITLE
can balances be ints?

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/go-stellar-base#23]
Can we make the Balance an integer rather than a string? in responses.go

```
type Balance struct {
	Balance string `json:"balance"`
	Limit   string `json:"limit,omitempty"`
	Asset
}
```

**Comment by bartekn** [comment]
There is [`amount` package](https://github.com/stellar/go-stellar-base/tree/master/amount) that helps converting numbers to/from the format used internally in stellar-core.

**Comment by nullstyle** [comment]
It doesn't make sense to me.  This struct is specifically "The representation that horizon uses", which is a string.
