### ISSUE TITLE
getting the XLM balance from an account

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/go-stellar-base#24]
This seems like a really common thing people will want to do. right now it is a bit cumbersome. I know you are trying to have this account struct mirror what is returned by horizon but maybe having the XLM balance be directly in the struct would be better?
https://github.com/stellar/go-stellar-base/blob/master/horizon/responses.go#L13
@nullstyle @bartekn

**Comment by bartekn** [comment]
I think we can simply add `GetNativeBalance()` method to `Account` struct.

**Comment by nullstyle** [comment]
Yeah, I think @bartekn has the right idea.   Those structs must mirror the JSON responses from CLI (given how encoding/json works in go), and I think our default representation of balance data shouldn't privilege lumens, but there is no harm in adding a methods that make the access easier in the few cases it is useful.

**Comment by bartekn** [comment]
In PR: https://github.com/stellar/go-stellar-base/pull/26
