### ISSUE TITLE
Implement missing operations

### ISSUE THREAD

**Issue by bartekn** [stellar/go-stellar-base#28]
- [x] Create Account
- [x] Payment
- [x] Path Payment
- [ ] Manage Offer
- [ ] Create Passive Offer
- [ ] Set Options
- [x] Change Trust (https://github.com/stellar/go-stellar-base/pull/29)
- [x] Allow Trust
- [ ] Account Merge
- [ ] Inflation
- [x] Manage Data

**Comment by bartekn** [comment]
# API proposal

## Manage Offer / Create Passive Offer
```go
type Amount string

type Price struct {
	Numerator   int32
	Denominator int32
}

// NewPrice approximates price represented as string
func NewPrice(price string) (Price, error) {}

type Rate struct {
	Selling Asset // Existing Asset struct
	Buying  Asset
	Price
}

// CreateOffer creates an offer
// OfferID in the XDR op will be set to `0`.
func CreateOffer(rate Rate, amount Amount) ManageOfferBuilder {}
// CreatePassiveOffer creates passive offer
func CreatePassiveOffer(rate Rate, amount Amount) ManageOfferBuilder {}

// UpdateOffer updates an offer
func UpdateOffer(rate Rate, amount Amount, id uint64) ManageOfferBuilder {}

// DeleteOffer deletes an offer
// Amount in the XDR op will be set to `0`.
func DeleteOffer(rate Rate, id uint64) ManageOfferBuilder {}

// ExampleManageOffer ...
func ExampleManageOffer() {
	rate := Rate{
		Selling: CreditAsset("USD", "GBA"),
		Buying:  NativeAsset(),
		Price:   ApproximatePrice("5"),
	}

	Transaction(
		SourceAccount{seed},
		Sequence{1},
		CreateOffer(rate, "20"),
		UpdateOffer(rate, "20", 2),
		DeleteOffer(rate, 1),
	)
}
```
## Account Merge
```go
// I think we can change Destination mutator to string
// Right now it looks like this:
//
//    type Destination struct {
//      AddressOrSeed string
//    }
//
// But there is no operation that requires destination's seed
type Destination string

func (m Destination) MutateAccountMerge() {}
```

## Inflation
```go
type InflationBuilder struct {
	O xdr.Operation
}

func Inflation() InflationBuilder {}
```

## Set Options
```go
type AccountFlag int

const (
	AuthRequiredFlag  AccountFlag = 1
	AuthRevocableFlag AccountFlag = 2
	AuthImmutableFlag AccountFlag = 4
)

// Mutators
type InflationDest Destination
type HomeDomain string
type SetFlags uint32
type ClearFlags uint32
type Weights struct {
	Master *uint32
	Low    *uint32
	Medium *uint32
	High   *uint32
}
type Signer struct {
	PublicKey string
	Weight    uint32
}

// Helpers

// Weight simply returns pointer to w.
// It makes setting weights easier (check example below).
func Weight(w uint32) *uint32 {
	return &w
}

func SetFlags(flags ...AccountFlag) SetFlags {
	// Logical OR
}

func ClearFlags(flags ...AccountFlag) ClearFlags {
	// Logical OR
}

func AddSigner(publicKey string, weight uint32) Signer {
	return Signer{publicKey, weight}
}
func RemoveSigner(publicKey string) Signer {
	return Signer{publicKey, 0}
}

// ExampleSetOptions ...
func ExampleSetOptions() {
	Transaction(
		SourceAccount{seed},
		Sequence{1},
		SetOptions(
			InflationDest("GBA"),
			HomeDomain("stellar.org"),
			SetFlags(AuthRequiredFlag, AuthImmutableFlag),
			ClearFlags(AuthRevocableFlag),
			Weights{
				Master: Weight(3),
				High:   Weight(5),
			},
			AddSigner("GAA", 5),
		),
		SetOptions(
			RemoveSigner("GCC"),
		)
	)
}
```

**Comment by nullstyle** [comment]
I'm just going to leave some comments as I think of them in regards to this proposal.

First thing:  We shouldn't be adding `Price` to the build package.  `xdr.Price` is equivalent to what you propose.  Instead, I would be fine with using `type Price string`.  That would allow us to hang mutations off of it while keeping the usage simple.  My goal for using the `build` package is to minimize the need for the usual go error management of `if err != nil`, since it can obfuscate meaning.  Instead, your code runs a bunch of mutators using `Transaction()` and then one error pops out.

Does that make sense?

**Comment by nullstyle** [comment]
Before I make some more comments regarding offer designs, I want to comment on `SetOptions`.  IMO, the `SetOptions` mutator is nice to allow someone to group multiple changes into a single operation (to save on fees), our examples shouldn't push that model... it's just more complicated when the majority case is going to be one change per SetOptions operation.

Instead, we should allow:
```go
func ExampleSetOptions() {
    Transaction(
        SourceAccount{seed},
        Sequence{1},
        AddSigner("GAA", 5),
    )
}
```

Luckily, this is trivial... simply implement `MutateTransaction` for the mutator as well as `MutateOperation`

**Comment by nullstyle** [comment]
More comments regarding SetOptions:

You're design for setting account thresholds and the master key's weight are confusing.  While the thresholds and the master weight are packed into a single int in the ledger to save space, logically we should keep the thresholds separate from weights.  

I think a better interface for the thresholds would be:

```
// Sets all three thresholds as a group: low, med, high
SetThresholds(0, 0, 2)

// Set them one at a time when more control is needed
SetLowThreshold(1)
SetMedThreshold(0)
SetHighThreshold(3)
```

I believe this model is better because it doesn't involve the `Weight` helper which is IMO clunky.

**Comment by nullstyle** [comment]
I don't like your redefinition of the xdr constants for flags.  If we're going to use `SetFlags` and `ClearFlags` as the API, we should use the XDR constants directly.

IMO, I think it we should also add simple helpers to set/clear flags:  `SetAuthRequired()`, `ClearAuthRequired()`, etc.  These are simpler to use except in when being editted by a client application, which I am assuming will present a checkbox-like interface to users.

**Comment by nullstyle** [comment]
Regarding the flag constants, we should at the very least use the xdr constants in the redefinition:

`AuthRequiredFlag = xdr.AccountFlagsAuthRequiredFlag`

**Comment by nullstyle** [comment]
Also note, idiomatic go often uses prefixes for constant grouping:  `FlagAuthRequired` instead of `AuthRequiredFlag`

**Comment by nullstyle** [comment]
Alright, after thinking about offers some more... I think you've got a great design.  The notes I mentioned about price in my first comment are my only issues.
